[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
direct-distribute-airdrop = "GaHqnnZv2CeZYEA23V1zGuADSFhWnJZSmFzLeje1H2T1"
nonce-verify = "4U17W5WH9JJQZK9HcZaD9mYhWehhBSyymAoG6gMYj5CW"
solana_airdrop = "GMznVrvA9P4WfBzJPWq92BWmsBMQUo6pb8B7CMSvgX9n"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx vitest --run "

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "4U17W5WH9JJQZK9HcZaD9mYhWehhBSyymAoG6gMYj5CW"
program = "target/deploy/nonce_verify.so"

[[test.genesis]]
address = "GMznVrvA9P4WfBzJPWq92BWmsBMQUo6pb8B7CMSvgX9n"
program = "target/deploy/solana_airdrop.so"
