[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nonce-verify = "4U17W5WH9JJQZK9HcZaD9mYhWehhBSyymAoG6gMYj5CW"
solana_airdrop = "GMznVrvA9P4WfBzJPWq92BWmsBMQUo6pb8B7CMSvgX9n"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
