@startuml 03.使用nonce-verify的业务流程
  title 使用nonce-verify的业务流程

  actor user as "业务/用户"

  box "项目方"
    participant prj_contract as "项目方-链上合约"
    participant prj_backend as "项目方-后端"
  end box

  box "NonceVerify"
    participant contract as "NonceVerify合约"
    participant sdk as "NonceVerify SDK"
  end box

  autoactivate on 

  == 项目注册，创建项目方账户 ==
  autonumber

  prj_backend -> sdk : 注册项目（合约地址， 项目authority地址）
    sdk -> contract: 注册项目，创建项目账户
      note over contract
        可以根据配置控制，是否收费用;
        ....
        根据配置，是否需要授权
      end note 
    return
  return 

  == 生成 offchain-sign ==
  autonumber
  
  prj_backend -> sdk: 读取用户nonce(项目合约地址， 用户账户)
    sdk -> contract: 读取用户账户数据
    return
    note over sdk
      如果用户账户不存在，nonce取0；
      ....
      如果用户账户存在，但该项目合约不存在，则nonce取0；
      ....
      取用户账户数据中，该项目合约对应的nonce值；
    end note 

  return: nonce值

  prj_backend -> prj_backend: 生成签名数据, 并存储
  deactivate

  == 业务使用 offchain-sign ==
  autonumber

  user -> prj_backend: 获取offchain-sign
  return

  user -> prj_contract: 业务交易（offchain-sign数据，业务数据）
    prj_contract -> contract: 验证nonce，并自增nonce(项目合约地址， 用户账户, nonce)
      note over contract
        1. 不存在的账户要创建；账户空间不足的要扩展，fee payer 由项目方指定；
        （一般情况下是用户支付）
        2. 需要验证项目合约的authority；
        ----
        3. 对于已经不存在的项目方地址，可以清理其对应的nonce,并复用空间；
        尽量减少空间浪费；
        ----
        4. 可以在这里收取费用；
      end note 
    return <color:Red>返回验证是否通过，验证失败交易要失败.</color>

    prj_contract -> prj_contract: 执行自己的业务逻辑
    deactivate
  return

  == 其他 ==
  note over user, contract
  1, 用户可以注销自己的nonce账户，获取账户的租金费用；但是以后再用则要创建；
  2, 项目方也可以注销自己的项目方账户
  end note 

@enduml