@startuml 01.空投合约账户结构
  title 空投合约账户结构

  left to right direction

  package "airdrop-program" {

    struct AirdropProjectAccount<<PDA>> {
      <color:DarkGreen><b>// 代表一个空投项目
      ====
      admin: Pubkey, <color:DarkGreen>// 空投管理员账户
      ....
      id: Pubkey, <color:DarkGreen>//AirdropProjectAccount 的 pda seed
    }
    

    struct AirdropMintAccountAuthority<<PDA>>{
      <color:DarkGreen><b>// 代表空投mint合约的authority账户
      ====
    }
    AirdropProjectAccount )--> AirdropMintAccountAuthority : PDA seed


    struct AirdropNonceBusinessAccountAuthority<<PDA>> {
      <color:DarkGreen><b>// 代表空投nonce合约的authority账户
      ====
    }
    AirdropProjectAccount )--> AirdropNonceBusinessAccountAuthority : PDA seed
  }


  package "nonce-verify-program" {
    struct NonceProjectAccount <<PDA>>{
      <color:DarkGreen><b>// 代表一个nonce项目
      ====
      admin: Pubkey, <color:DarkGreen>// 管理账户，提款管理，注册管理（可选）
      ....
      id: Pubkey, <color:DarkGreen>//NonceProjectAccount 的 pda seed
      ----
      <color:DarkGreen><b>// PDA 账户， seed = id
      vault: Pubkey, <color:DarkGreen>// 用于存放fee的账户， 
    }

    struct BusinessNonceProjectAccount <<PDA>> {
      <color:DarkGreen><b>// 代表一个nonce 的 business 项目, 由项目方创建
      ====
      id: Pubkey, <color:DarkGreen>//NonceProjectAccount 的 pda seed
      ....
      authority: Pubkey, <color:DarkGreen>// 修改它所属的用户nonce时，需要签名
    }
    NonceProjectAccount )--> BusinessNonceProjectAccount : PDA seed


    struct UserBusinessNonceStateAccount <<PDA>> {
      <color:DarkGreen><b>// 代表一个用户在一个project中的nonce状态
      ====
      nonce: u64, <color:DarkGreen>// nonce值
      ....
      user: Pubkey, <color:DarkGreen>// 用户账户
    }
    BusinessNonceProjectAccount )--> UserBusinessNonceStateAccount : PDA seed
  }

  AirdropNonceBusinessAccountAuthority --[#Blue]-> BusinessNonceProjectAccount::authority : nonce authority

  package "SPL-program" {
    struct AnyMintAccount {
      <color:DarkGreen><b>// 代表一个用于空投的mint合约
      ====
    }
  }
  AirdropMintAccountAuthority -[#Blue]-> AnyMintAccount : mint authority



@enduml

'-------------------------------------------------------------

@startuml 02.业务流程
  title 业务流程-流程图

|#LightGreen|manage| 管理侧
|#LightBlue|user| 用户侧

|manage|
  start

  :airdrop-account已经准备就绪;

  :准备待空投合约（mint-account）;

  :计算该mint合约的authority账户(这个authority账户是空投合约的pda账户);

  :创建空投合约（或者，将空投合约的authority转移给给上一步计算所得的authority）;

  :计算用户的待签名数据，使用airdrop-account中指定的管理账户对数据进行签名（off-sign签名）;

|user|
  :拿到off-sign签名数据;

  :发起交易，申领空投;

@enduml

'-------------------------------------------------------------

